export interface AppDef {
  name: string;
  icon: string;
  desc: string;
  _i: number;
}

export function appColor(idx: number) {
  const h = (idx * 137.508) % 360;
  const s = 72 + (idx % 3) * 6;
  const l = 56 + (idx % 4) * 4;
  return {
    bg: `hsla(${h}, ${s}%, ${l}%, 0.13)`,
    border: `hsla(${h}, ${s}%, ${l}%, 0.28)`,
    text: `hsl(${h}, ${s}%, ${l}%)`,
  };
}

export const APPS: AppDef[] = [
  { name: "Firewall Guard", icon: "lucide:shield", desc: "Network security and threat monitoring" },
  { name: "Compute Engine", icon: "lucide:cpu", desc: "Scalable cloud compute instances" },
  { name: "Data Vault", icon: "lucide:database", desc: "Managed SQL and NoSQL databases" },
  { name: "CDN Express", icon: "lucide:globe", desc: "Global content delivery network" },
  { name: "Pipeline CI", icon: "lucide:zap", desc: "Continuous integration and deployment" },
  { name: "Auth Shield", icon: "lucide:lock", desc: "Identity and access management" },
  { name: "Metrics Hub", icon: "lucide:bar-chart-3", desc: "Real-time analytics and dashboards" },
  { name: "Config Center", icon: "lucide:settings", desc: "Centralized configuration management" },
  { name: "Stack Builder", icon: "lucide:layers", desc: "Infrastructure as code composer" },
  { name: "Terminal Pro", icon: "lucide:terminal", desc: "Cloud shell and remote access" },
  { name: "Mail Relay", icon: "lucide:mail", desc: "Transactional email service" },
  { name: "Media Studio", icon: "lucide:camera", desc: "Image and video processing" },
  { name: "Scheduler", icon: "lucide:calendar", desc: "Cron jobs and task scheduling" },
  { name: "Notifier", icon: "lucide:bell", desc: "Push notifications and alerts" },
  { name: "Docs Portal", icon: "lucide:book-open", desc: "API documentation generator" },
  { name: "Biz Tracker", icon: "lucide:briefcase", desc: "Project and resource management" },
  { name: "Cloud Sync", icon: "lucide:cloud", desc: "Object storage and file sync" },
  { name: "Route Finder", icon: "lucide:compass", desc: "API gateway and traffic routing" },
  { name: "Pay Gateway", icon: "lucide:credit-card", desc: "Payment processing and billing" },
  { name: "Deploy Bot", icon: "lucide:rocket", desc: "Automated release management" },
  { name: "Log Stream", icon: "lucide:scroll-text", desc: "Centralized logging and search" },
  { name: "Secret Store", icon: "lucide:key-round", desc: "Secrets and credential vault" },
  { name: "DNS Manager", icon: "lucide:globe-lock", desc: "Domain name and DNS management" },
  { name: "Container Ops", icon: "lucide:box", desc: "Container orchestration platform" },
  { name: "Edge Functions", icon: "lucide:satellite", desc: "Serverless edge computing" },
  { name: "Vault Backup", icon: "lucide:hard-drive", desc: "Automated backup and recovery" },
  { name: "Mesh Net", icon: "lucide:network", desc: "Service mesh and networking" },
  { name: "Monitor AI", icon: "lucide:activity", desc: "AI-powered uptime monitoring" },
  { name: "Workflow Engine", icon: "lucide:git-branch", desc: "Visual workflow automation" },
  { name: "Queue Hub", icon: "lucide:list-ordered", desc: "Message queue and event streaming" },
  { name: "Form Builder", icon: "lucide:text-cursor-input", desc: "Drag-and-drop form designer" },
  { name: "A/B Lab", icon: "lucide:flask-conical", desc: "Experimentation and feature flags" },
  { name: "Search Index", icon: "lucide:search", desc: "Full-text search as a service" },
  { name: "IOT Bridge", icon: "lucide:wifi", desc: "IoT device management hub" },
  { name: "Geo Mapper", icon: "lucide:map-pin", desc: "Geolocation and mapping services" },
  { name: "Chat Engine", icon: "lucide:message-circle", desc: "Real-time chat and messaging" },
  { name: "Translate AI", icon: "lucide:languages", desc: "Machine translation API" },
  { name: "ML Studio", icon: "lucide:brain", desc: "Machine learning model training" },
  { name: "Data Lake", icon: "lucide:droplets", desc: "Big data storage and analytics" },
  { name: "Registry", icon: "lucide:package", desc: "Container and artifact registry" },
  { name: "Trace Path", icon: "lucide:radar", desc: "Distributed tracing and debugging" },
  { name: "Cost Lens", icon: "lucide:piggy-bank", desc: "Cloud cost optimization" },
  { name: "Compliance", icon: "lucide:shield-check", desc: "Regulatory compliance scanner" },
  { name: "Incident Hub", icon: "lucide:siren", desc: "Incident response management" },
  { name: "Repo Mirror", icon: "lucide:git-merge", desc: "Git repository mirroring" },
  { name: "Label Studio", icon: "lucide:tag", desc: "Data annotation and labeling" },
  { name: "Graph DB", icon: "lucide:share-2", desc: "Graph database service" },
  { name: "Time Series", icon: "lucide:trending-up", desc: "Time-series data platform" },
  { name: "Pub Sub", icon: "lucide:radio", desc: "Publish-subscribe messaging" },
  { name: "OCR Service", icon: "lucide:scan-text", desc: "Optical character recognition" },
  { name: "Speech API", icon: "lucide:mic", desc: "Speech-to-text and text-to-speech" },
  { name: "Vision AI", icon: "lucide:eye", desc: "Image recognition and analysis" },
  { name: "Doc Sign", icon: "lucide:signature", desc: "Electronic document signing" },
  { name: "Survey Tool", icon: "lucide:clipboard-list", desc: "Surveys and feedback collection" },
  { name: "Wiki Space", icon: "lucide:notebook-pen", desc: "Team knowledge base" },
  { name: "Ticket Desk", icon: "lucide:headset", desc: "Customer support ticketing" },
  { name: "Board Planner", icon: "lucide:kanban", desc: "Kanban-style project boards" },
  { name: "Time Tracker", icon: "lucide:clock", desc: "Time tracking and timesheets" },
  { name: "Meet Hub", icon: "lucide:video", desc: "Video conferencing platform" },
  { name: "Screen Share", icon: "lucide:monitor", desc: "Screen sharing and remote control" },
  { name: "Feed Reader", icon: "lucide:rss", desc: "RSS feed aggregator" },
  { name: "Bookmark Vault", icon: "lucide:bookmark", desc: "Save and organize bookmarks" },
  { name: "Password Safe", icon: "lucide:key", desc: "Password manager and generator" },
  { name: "Link Short", icon: "lucide:link", desc: "URL shortener and analytics" },
  { name: "QR Studio", icon: "lucide:qr-code", desc: "QR code generator and scanner" },
  { name: "PDF Tools", icon: "lucide:file-text", desc: "PDF conversion and editing" },
  { name: "Spreadsheet", icon: "lucide:table", desc: "Online spreadsheet editor" },
  { name: "Slides Maker", icon: "lucide:presentation", desc: "Presentation builder" },
  { name: "Code Editor", icon: "lucide:code", desc: "Online code editor and IDE" },
  { name: "API Tester", icon: "lucide:plug", desc: "REST and GraphQL API client" },
  { name: "DB Admin", icon: "lucide:table-2", desc: "Database management console" },
  { name: "Uptime Watch", icon: "lucide:heart-pulse", desc: "Uptime and health monitoring" },
  { name: "Load Tester", icon: "lucide:gauge", desc: "Load and stress testing" },
  { name: "SSL Cert", icon: "lucide:badge-check", desc: "SSL certificate management" },
  { name: "Email Inbox", icon: "lucide:inbox", desc: "Shared team email inbox" },
  { name: "Calendar Sync", icon: "lucide:calendar-days", desc: "Cross-platform calendar sync" },
  { name: "Contact Hub", icon: "lucide:contact", desc: "CRM and contact management" },
  { name: "Invoice Gen", icon: "lucide:receipt", desc: "Invoice generation and tracking" },
  { name: "Expense Log", icon: "lucide:wallet", desc: "Expense tracking and reports" },
  { name: "Inventory", icon: "lucide:package-search", desc: "Inventory management system" },
  { name: "Shipping", icon: "lucide:truck", desc: "Shipping and logistics tracker" },
  { name: "Analytics Pro", icon: "lucide:line-chart", desc: "Web and app analytics" },
  { name: "Heatmapper", icon: "lucide:grid-3x3", desc: "User behavior heatmaps" },
  { name: "Session Reel", icon: "lucide:film", desc: "Session recording and replay" },
  { name: "User Lab", icon: "lucide:users", desc: "User research and testing" },
  { name: "Design Sys", icon: "lucide:palette", desc: "Design system and component lib" },
  { name: "Asset Bank", icon: "lucide:image", desc: "Digital asset management" },
  { name: "Font Picker", icon: "lucide:type", desc: "Web font management tool" },
  { name: "Color Lab", icon: "lucide:pipette", desc: "Color palette generator" },
  { name: "Icon Studio", icon: "lucide:shapes", desc: "Icon design and management" },
  { name: "Wireframe", icon: "lucide:layout-grid", desc: "Wireframing and prototyping" },
  { name: "Diagram", icon: "lucide:workflow", desc: "Flowchart and diagram editor" },
  { name: "Mind Map", icon: "lucide:brain-circuit", desc: "Mind mapping and brainstorming" },
  { name: "Whiteboard", icon: "lucide:pencil", desc: "Collaborative whiteboard" },
  { name: "Note Sync", icon: "lucide:sticky-note", desc: "Notes with real-time sync" },
  { name: "Task Flow", icon: "lucide:list-todo", desc: "Task management and to-dos" },
  { name: "Habit Tracker", icon: "lucide:target", desc: "Goal and habit tracking" },
  { name: "Pomodoro", icon: "lucide:timer", desc: "Focus timer and productivity" },
  { name: "File Convert", icon: "lucide:file-code-2", desc: "File format converter" },
  { name: "Compress Pro", icon: "lucide:file-archive", desc: "File compression and archiving" },
  { name: "Batch Rename", icon: "lucide:file-pen", desc: "Bulk file renaming tool" },
  { name: "Diff Viewer", icon: "lucide:git-compare", desc: "File and text diff tool" },
  { name: "Snippet Vault", icon: "lucide:file-code", desc: "Code snippet manager" },
].map((app, i) => ({ ...app, _i: i }));
