import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  chooseProvider: "Pilih penyedia SSO anda",
  selectProvider: "Pilih penyedia SSO yang dikonfigurasikan untuk meneruskan",
  providerEntraId: "Microsoft Entra ID",
  providerGithub: "GitHub OAuth",
  providerOkta: "Okta",
  protocolSaml: "SAML 2.0",
  protocolOidc: "OIDC",
  continueWithProvider: "Teruskan dengan penyedia yang dipilih",
  continueWithSSO: "Teruskan dengan SSO",
  orUse: "Atau guna",
  adLdap: "AD / LDAP",
  localAccount: "Akaun Tempatan",
  pageSso: "Halaman 1 daripada 3 - Penyedia SSO",
  skipToLocal: "Langkau ke akaun tempatan",

  localTitle: "Tempatan",
  localSubtitle: "Log Masuk Akaun",
  localDesc: "Log masuk dengan nama pengguna dan kata laluan",
  emailOrUsername: "E-mel atau Nama Pengguna",
  placeholderEmail: "anda@syarikat.com",
  password: "Kata Laluan",
  enterPassword: "Masukkan kata laluan anda",
  rememberMe: "Ingat saya",
  forgotPassword: "Lupa kata laluan?",
  signIn: "Log masuk",
  orOtherMethods: "Atau guna kaedah lain",
  ssoProviders: "Penyedia SSO",
  pageLocal: "Halaman 3 daripada 3 - Pengesahan Tempatan",
  noAccount: "Tiada akaun?",

  adTitle: "AD",
  adSubtitle: "/ Log Masuk LDAP",
  adDesc: "Masukkan kredensial domain anda",
  errorFillFields: "Sila isi semua medan",
  domain: "Domain",
  placeholderDomain: "domain.tempatan",
  username: "Nama Pengguna",
  placeholderDomainUser: "DOMAIN\\namapengguna",
  networkPassword: "Kata laluan rangkaian",
  rememberDomain: "Ingat domain",
  useLocalAccount: "Guna akaun tempatan",
  signInDomain: "Log masuk ke Domain",
  or: "Atau",
  backToSSO: "Kembali ke penyedia SSO",
  pageAdLdap: "Halaman 2 daripada 3 - Pengesahan AD/LDAP",

  checkEmail: "Semak e-mel anda",
  resetPassword: "Tetapkan semula kata laluan",
  resetLinkSent: "Jika akaun wujud dengan e-mel tersebut, anda akan menerima pautan tetapan semula sebentar lagi.",
  resetDesc: "Masukkan e-mel anda dan kami akan hantar pautan untuk menetapkan semula kata laluan.",
  tryAgain: "Tidak menerimanya? Cuba lagi",
  emailAddress: "Alamat e-mel",
  sendResetLink: "Hantar pautan tetapan semula",
  backToLogin: "Kembali ke log masuk",

  registerTitle: "Buat akaun",
  registerDesc: `Dapatkan akses ke suite ${BRAND.name} penuh.`,
  firstName: "Nama pertama",
  placeholderFirstName: "Ahmad",
  lastName: "Nama terakhir",
  placeholderLastName: "Razak",
  email: "E-mel",
  minChars: "Min. 8 aksara",
  confirmPassword: "Sahkan kata laluan",
  reenterPassword: "Masukkan semula kata laluan",
  agreeTo: "Saya bersetuju dengan",
  and: "dan",
  termsOfService: "Terma Perkhidmatan",
  privacyPolicy: "Dasar Privasi",
  createAccountBtn: "Buat akaun",
  alreadyHaveAccount: "Sudah mempunyai akaun?",

  manageTitle: "Pengurusan Log Masuk",
  manageSubtitle: "Konfigurasikan penyedia SSO dan kaedah pengesahan.",
  addProvider: "Tambah Penyedia",
  usersLabel: "pengguna",
  lastSync: "Segerak terakhir",

  usersTitle: "Pengguna",
  manageUsers: "Urus pengguna dan peranan mereka.",
  allUsers: "Semua Pengguna",
  addUser: "Tambah Pengguna",
  fullName: "Nama Penuh",
  cancel: "Batal",
  createUser: "Cipta Pengguna",
  colUser: "Pengguna",
  colRole: "Peranan",
  colStatus: "Status",
  colLastLogin: "Log Masuk Terakhir",
  colActions: "Tindakan",
  edit: "Sunting",
  delete: "Padam",
  roleAdmin: "Pentadbir",
  roleDirector: "Pengarah",
  roleManager: "Pengurus",
  roleStaff: "Kakitangan",
  roleAuditor: "Juruaudit",
  statusActive: "Aktif",
  statusInactive: "Tidak Aktif",
  statusSuspended: "Digantung",

  groupsTitle: "Peranan",
  manageGroups: "Urus peranan pengguna dan kebenaran.",
  allGroups: "Semua Peranan",
  addGroup: "Tambah Peranan",
  groupName: "Nama Peranan",
  description: "Penerangan",
  createGroup: "Cipta Peranan",
  members: "ahli",

  permissionsTitle: "Kebenaran",
  managePermissions: "Konfigurasikan kawalan akses berasaskan peranan.",
  permissionsMatrix: "Matriks Kebenaran Peranan",
  permDashboard: "Papan Pemuka",
  permHrPortal: "Portal HR",
  permFinance: "Kewangan",
  permReports: "Laporan",
  permAuditLog: "Log Audit",
  actionRead: "Baca",
  actionWrite: "Tulis",
  actionDelete: "Padam",
  actionUpdate: "Kemas kini",

  navNavigation: "Navigasi",
  navDashboard: "Papan Pemuka",
  navAuthProviders: "Penyedia Auth",
  navUsersAndApps: "Pengguna & Apl",
  navUserManagement: "Pengurusan Pengguna",
  navAppManagement: "Pengurusan Apl",
  navSettings: "Tetapan",
  navUserSettings: "Tetapan Pengguna",
  navUsers: "Pengguna",
  navAccess: "Akses",
  navAllUsers: "Semua Pengguna",
  navGroups: "Peranan",
  navPermissions: "Kebenaran",
  navManageUsers: "Pengguna",
  dashboardTitle: "Papan Pemuka",
  dashboardSubtitle: "Gambaran keseluruhan pengesahan dan kawalan akses.",
  statUsers: "Pengguna",
  statGroups: "Peranan",
  statProviders: "Penyedia",
  statActiveUsers: "Pengguna Aktif",
  statEnabled: "Dibenarkan",
  statDisabled: "Dilumpuhkan",
  infoTitle: "Butiran",
  infoCreatedBy: "Dicipta Oleh",
  infoCreatedAt: "Dicipta Pada",
  infoUpdatedBy: "Dikemaskini Oleh",
  infoUpdatedAt: "Dikemaskini Pada",
  localManageTitle: "Log Masuk Tempatan",
  localManageSubtitle: "Urus pengguna pengesahan tempatan.",
  labelName: "Nama",
  labelEmail: "E-mel",
  labelRole: "Peranan",
  labelStatus: "Status",
  saveUser: "Simpan Pengguna",
  editUser: "Sunting Pengguna",
  phUserName: "Nama penuh",
  phUserEmail: "pengguna@syarikat.com",
  providersTitle: "Penyedia Jauh",
  providersSubtitle: "Urus penyedia SSO dan pengesahan jauh.",
  editProvider: "Sunting Penyedia",
  providerName: "Nama Penyedia",
  providerType: "Jenis Penyedia",
  labelEnabled: "Dibenarkan",
  labelUserCount: "Kiraan Pengguna",
  labelLastSync: "Segerak Terakhir",
  saveProvider: "Simpan Penyedia",
  createProvider: "Cipta Penyedia",
  phProviderName: "cth. Google Workspace",
  phProviderType: "cth. OAuth 2.0",
  editGroup: "Sunting Peranan",
  saveGroup: "Simpan Peranan",
  colMembers: "Ahli",
  phGroupName: "Nama peranan",
  phGroupDesc: "Penerangan peranan",
  addRole: "Tambah Peranan",
  addResource: "Tambah Sumber",
  roleName: "Nama Peranan",
  resourceName: "Nama Sumber",
  createRole: "Cipta Peranan",
  createResource: "Cipta Sumber",
  navOverview: "Gambaran",
  navAuthentication: "Pengesahan",
  navLocalLogin: "Log Masuk Tempatan",
  navRemoteProviders: "Penyedia Jauh",
  navAccessControl: "Kawalan Akses",
  colInfo: "Maklumat",
  navRoles: "Peranan",
  manageUsersTitle: "Pengguna",
  manageUsersSubtitle: "Lihat semua pengguna dan tetapkan peranan mengikut penyedia log masuk.",
  colProvider: "Penyedia",
  filterAllProviders: "Semua Penyedia",
  filterAllRoles: "Semua Peranan",
  assignRole: "Tetapkan Peranan",
  providerLocal: "Tempatan",
  providerLdap: "LDAP",
  providerOAuth: "OAuth 2.0",
  providerSaml: "SAML 2.0",
  noUsersMatch: "Tiada pengguna sepadan dengan penapis semasa.",
  colUserCount: "Pengguna",
};

export default strings;
