import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  chooseProvider: "选择您的SSO提供商",
  selectProvider: "选择已配置的SSO提供商以继续",
  providerEntraId: "Microsoft Entra ID",
  providerGithub: "GitHub OAuth",
  providerOkta: "Okta",
  protocolSaml: "SAML 2.0",
  protocolOidc: "OIDC",
  continueWithProvider: "继续使用已选提供商",
  continueWithSSO: "继续使用SSO",
  orUse: "或使用",
  adLdap: "AD / LDAP",
  localAccount: "本地账户",
  pageSso: "第 1 页，共 3 页 - SSO 提供商",
  skipToLocal: "跳转到本地账户",

  localTitle: "本地",
  localSubtitle: "账户登录",
  localDesc: "使用用户名和密码登录",
  emailOrUsername: "邮箱或用户名",
  placeholderEmail: "you@company.com",
  password: "密码",
  enterPassword: "输入您的密码",
  rememberMe: "记住我",
  forgotPassword: "忘记密码？",
  signIn: "登录",
  orOtherMethods: "或使用其他方式",
  ssoProviders: "SSO 提供商",
  pageLocal: "第 3 页，共 3 页 - 本地认证",
  noAccount: "没有账户？",

  adTitle: "AD",
  adSubtitle: "/ LDAP 登录",
  adDesc: "输入您的域凭据",
  errorFillFields: "请填写所有字段",
  domain: "域名",
  placeholderDomain: "domain.local",
  username: "用户名",
  placeholderDomainUser: "DOMAIN\\username",
  networkPassword: "网络密码",
  rememberDomain: "记住域名",
  useLocalAccount: "使用本地账户",
  signInDomain: "登录到域",
  or: "或",
  backToSSO: "返回 SSO 提供商",
  pageAdLdap: "第 2 页，共 3 页 - AD/LDAP 认证",

  checkEmail: "查看您的邮箱",
  resetPassword: "重置密码",
  resetLinkSent: "如果该邮箱存在账户，您将很快收到重置链接。",
  resetDesc: "输入您的邮箱，我们将发送重置密码的链接。",
  tryAgain: "没有收到？再试一次",
  emailAddress: "邮箱地址",
  sendResetLink: "发送重置链接",
  backToLogin: "返回登录",

  registerTitle: "创建账户",
  registerDesc: `获取完整的 ${BRAND.name} 套件访问权限。`,
  firstName: "名",
  placeholderFirstName: "小明",
  lastName: "姓",
  placeholderLastName: "王",
  email: "邮箱",
  minChars: "最少 8 个字符",
  confirmPassword: "确认密码",
  reenterPassword: "重新输入密码",
  agreeTo: "我同意",
  and: "和",
  termsOfService: "服务条款",
  privacyPolicy: "隐私政策",
  createAccountBtn: "创建账户",
  alreadyHaveAccount: "已有账户？",

  manageTitle: "登录管理",
  manageSubtitle: "配置SSO提供商和身份验证方法。",
  addProvider: "添加提供商",
  usersLabel: "用户",
  lastSync: "上次同步",

  usersTitle: "用户",
  manageUsers: "管理用户及其角色。",
  allUsers: "所有用户",
  addUser: "添加用户",
  fullName: "全名",
  cancel: "取消",
  createUser: "创建用户",
  colUser: "用户",
  colRole: "角色",
  colStatus: "状态",
  colLastLogin: "上次登录",
  colActions: "操作",
  edit: "编辑",
  delete: "删除",
  roleAdmin: "管理员",
  roleDirector: "总监",
  roleManager: "经理",
  roleStaff: "员工",
  roleAuditor: "审计员",
  statusActive: "活跃",
  statusInactive: "未激活",
  statusSuspended: "已停用",

  groupsTitle: "角色",
  manageGroups: "管理用户角色和权限。",
  allGroups: "所有角色",
  addGroup: "添加角色",
  groupName: "角色名称",
  description: "描述",
  createGroup: "创建角色",
  members: "成员",

  permissionsTitle: "权限",
  managePermissions: "配置基于角色的访问控制。",
  permissionsMatrix: "角色权限矩阵",
  permDashboard: "仪表盘",
  permHrPortal: "人力资源门户",
  permFinance: "财务",
  permReports: "报表",
  permAuditLog: "审计日志",
  actionRead: "读取",
  actionWrite: "写入",
  actionDelete: "删除",
  actionUpdate: "更新",

  navNavigation: "导航",
  navDashboard: "仪表盘",
  navAuthProviders: "认证提供商",
  navUsersAndApps: "用户与应用",
  navUserManagement: "用户管理",
  navAppManagement: "应用管理",
  navSettings: "设置",
  navUserSettings: "用户设置",
  navUsers: "用户",
  navAccess: "访问",
  navAllUsers: "所有用户",
  navGroups: "角色",
  navPermissions: "权限",
  navManageUsers: "用户",
  dashboardTitle: "仪表盘",
  dashboardSubtitle: "认证和访问控制概览。",
  statUsers: "用户",
  statGroups: "角色",
  statProviders: "提供商",
  statActiveUsers: "活跃用户",
  statEnabled: "已启用",
  statDisabled: "已禁用",
  infoTitle: "详情",
  infoCreatedBy: "创建者",
  infoCreatedAt: "创建时间",
  infoUpdatedBy: "更新者",
  infoUpdatedAt: "更新时间",
  localManageTitle: "本地登录",
  localManageSubtitle: "管理本地认证用户。",
  labelName: "名称",
  labelEmail: "邮箱",
  labelRole: "角色",
  labelStatus: "状态",
  saveUser: "保存用户",
  editUser: "编辑用户",
  phUserName: "全名",
  phUserEmail: "user@company.com",
  providersTitle: "远程提供商",
  providersSubtitle: "管理SSO和远程认证提供商。",
  editProvider: "编辑提供商",
  providerName: "提供商名称",
  providerType: "提供商类型",
  labelEnabled: "已启用",
  labelUserCount: "用户数",
  labelLastSync: "上次同步",
  saveProvider: "保存提供商",
  createProvider: "创建提供商",
  phProviderName: "例如 Google Workspace",
  phProviderType: "例如 OAuth 2.0",
  editGroup: "编辑角色",
  saveGroup: "保存角色",
  colMembers: "成员",
  phGroupName: "角色名称",
  phGroupDesc: "角色描述",
  addRole: "添加角色",
  addResource: "添加资源",
  roleName: "角色名称",
  resourceName: "资源名称",
  createRole: "创建角色",
  createResource: "创建资源",
  navOverview: "概览",
  navAuthentication: "认证",
  navLocalLogin: "本地登录",
  navRemoteProviders: "远程提供商",
  navAccessControl: "访问控制",
  colInfo: "信息",
  navRoles: "角色",
  manageUsersTitle: "用户",
  manageUsersSubtitle: "查看所有用户并按登录提供商分配角色。",
  colProvider: "提供商",
  filterAllProviders: "所有提供商",
  filterAllRoles: "所有角色",
  assignRole: "分配角色",
  providerLocal: "本地",
  providerLdap: "LDAP",
  providerOAuth: "OAuth 2.0",
  providerSaml: "SAML 2.0",
  noUsersMatch: "没有用户匹配当前筛选条件。",
  colUserCount: "用户",
};

export default strings;
