import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  chooseProvider: "Choose your SSO provider",
  selectProvider: "Select a configured SSO provider to continue",
  providerEntraId: "Microsoft Entra ID",
  providerGithub: "GitHub OAuth",
  providerOkta: "Okta",
  protocolSaml: "SAML 2.0",
  protocolOidc: "OIDC",
  continueWithProvider: "Continue with selected provider",
  continueWithSSO: "Continue with SSO",
  orUse: "Or use",
  adLdap: "AD / LDAP",
  localAccount: "Local Account",
  pageSso: "Page 1 of 3 - SSO Providers",
  skipToLocal: "Skip to local account",

  localTitle: "Local",
  localSubtitle: "Account Login",
  localDesc: "Sign in with username and password",
  emailOrUsername: "Email or Username",
  placeholderEmail: "you@company.com",
  password: "Password",
  enterPassword: "Enter your password",
  rememberMe: "Remember me",
  forgotPassword: "Forgot password?",
  signIn: "Sign in",
  orOtherMethods: "Or use other methods",
  ssoProviders: "SSO Providers",
  pageLocal: "Page 3 of 3 - Local Authentication",
  noAccount: "Don't have an account?",

  adTitle: "AD",
  adSubtitle: "/ LDAP Login",
  adDesc: "Enter your domain credentials",
  errorFillFields: "Please fill in all fields",
  domain: "Domain",
  placeholderDomain: "domain.local",
  username: "Username",
  placeholderDomainUser: "DOMAIN\\username",
  networkPassword: "Network password",
  rememberDomain: "Remember domain",
  useLocalAccount: "Use local account",
  signInDomain: "Sign in to Domain",
  or: "Or",
  backToSSO: "Back to SSO providers",
  pageAdLdap: "Page 2 of 3 - AD/LDAP Authentication",

  checkEmail: "Check your email",
  resetPassword: "Reset password",
  resetLinkSent: "If an account exists with that email, you'll receive a reset link shortly.",
  resetDesc: "Enter your email and we'll send you a link to reset your password.",
  tryAgain: "Didn't receive it? Try again",
  emailAddress: "Email address",
  sendResetLink: "Send reset link",
  backToLogin: "Back to login",

  registerTitle: "Create an account",
  registerDesc: `Get access to the full ${BRAND.name} suite.`,
  firstName: "First name",
  placeholderFirstName: "John",
  lastName: "Last name",
  placeholderLastName: "Doe",
  email: "Email",
  minChars: "Min. 8 characters",
  confirmPassword: "Confirm password",
  reenterPassword: "Re-enter your password",
  agreeTo: "I agree to the",
  and: "and",
  termsOfService: "Terms of Service",
  privacyPolicy: "Privacy Policy",
  createAccountBtn: "Create account",
  alreadyHaveAccount: "Already have an account?",

  manageTitle: "Login Management",
  manageSubtitle: "Configure SSO providers and authentication methods.",
  addProvider: "Add Provider",
  usersLabel: "users",
  lastSync: "Last sync",

  usersTitle: "Users",
  manageUsers: "Manage users and their roles.",
  allUsers: "All Users",
  addUser: "Add User",
  fullName: "Full Name",
  cancel: "Cancel",
  createUser: "Create User",
  colUser: "User",
  colRole: "Role",
  colStatus: "Status",
  colLastLogin: "Last Login",
  colActions: "Actions",
  edit: "Edit",
  delete: "Delete",
  roleAdmin: "Admin",
  roleDirector: "Director",
  roleManager: "Manager",
  roleStaff: "Staff",
  roleAuditor: "Auditor",
  statusActive: "Active",
  statusInactive: "Inactive",
  statusSuspended: "Suspended",

  groupsTitle: "Groups",
  manageGroups: "Manage user groups and memberships.",
  allGroups: "All Groups",
  addGroup: "Add Group",
  groupName: "Group Name",
  description: "Description",
  createGroup: "Create Group",
  members: "members",

  permissionsTitle: "Permissions",
  managePermissions: "Configure role-based access control.",
  permissionsMatrix: "Role Permissions Matrix",
  permDashboard: "Dashboard",
  permHrPortal: "HR Portal",
  permFinance: "Finance",
  permReports: "Reports",
  permAuditLog: "Audit Log",
  actionRead: "Read",
  actionWrite: "Write",
  actionDelete: "Delete",
  actionUpdate: "Update",

  navNavigation: "Navigation",
  navDashboard: "Dashboard",
  navAuthProviders: "Auth Providers",
  navUsersAndApps: "Users & Apps",
  navUserManagement: "User Management",
  navAppManagement: "App Management",
  navSettings: "Settings",
  navUserSettings: "User Settings",
  navUsers: "Users",
  navAccess: "Access",
  navAllUsers: "All Users",
  navGroups: "Groups",
  navPermissions: "Permissions",
};

export default strings;
