import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  chooseProvider: "Pilih penyedia SSO anda",
  selectProvider: "Pilih penyedia SSO yang dikonfigurasikan untuk meneruskan",
  providerEntraId: "Microsoft Entra ID",
  providerGithub: "GitHub OAuth",
  providerOkta: "Okta",
  protocolSaml: "SAML 2.0",
  protocolOidc: "OIDC",
  continueWithProvider: "Teruskan dengan penyedia yang dipilih",
  continueWithSSO: "Teruskan dengan SSO",
  orUse: "Atau guna",
  adLdap: "AD / LDAP",
  localAccount: "Akaun Tempatan",
  pageSso: "Halaman 1 daripada 3 - Penyedia SSO",
  skipToLocal: "Langkau ke akaun tempatan",

  localTitle: "Tempatan",
  localSubtitle: "Log Masuk Akaun",
  localDesc: "Log masuk dengan nama pengguna dan kata laluan",
  emailOrUsername: "E-mel atau Nama Pengguna",
  placeholderEmail: "anda@syarikat.com",
  password: "Kata Laluan",
  enterPassword: "Masukkan kata laluan anda",
  rememberMe: "Ingat saya",
  forgotPassword: "Lupa kata laluan?",
  signIn: "Log masuk",
  orOtherMethods: "Atau guna kaedah lain",
  ssoProviders: "Penyedia SSO",
  pageLocal: "Halaman 3 daripada 3 - Pengesahan Tempatan",
  noAccount: "Tiada akaun?",

  adTitle: "AD",
  adSubtitle: "/ Log Masuk LDAP",
  adDesc: "Masukkan kredensial domain anda",
  errorFillFields: "Sila isi semua medan",
  domain: "Domain",
  placeholderDomain: "domain.tempatan",
  username: "Nama Pengguna",
  placeholderDomainUser: "DOMAIN\\namapengguna",
  networkPassword: "Kata laluan rangkaian",
  rememberDomain: "Ingat domain",
  useLocalAccount: "Guna akaun tempatan",
  signInDomain: "Log masuk ke Domain",
  or: "Atau",
  backToSSO: "Kembali ke penyedia SSO",
  pageAdLdap: "Halaman 2 daripada 3 - Pengesahan AD/LDAP",

  checkEmail: "Semak e-mel anda",
  resetPassword: "Tetapkan semula kata laluan",
  resetLinkSent: "Jika akaun wujud dengan e-mel tersebut, anda akan menerima pautan tetapan semula sebentar lagi.",
  resetDesc: "Masukkan e-mel anda dan kami akan hantar pautan untuk menetapkan semula kata laluan.",
  tryAgain: "Tidak menerimanya? Cuba lagi",
  emailAddress: "Alamat e-mel",
  sendResetLink: "Hantar pautan tetapan semula",
  backToLogin: "Kembali ke log masuk",

  registerTitle: "Buat akaun",
  registerDesc: `Dapatkan akses ke suite ${BRAND.name} penuh.`,
  firstName: "Nama pertama",
  placeholderFirstName: "Ahmad",
  lastName: "Nama terakhir",
  placeholderLastName: "Razak",
  email: "E-mel",
  minChars: "Min. 8 aksara",
  confirmPassword: "Sahkan kata laluan",
  reenterPassword: "Masukkan semula kata laluan",
  agreeTo: "Saya bersetuju dengan",
  and: "dan",
  termsOfService: "Terma Perkhidmatan",
  privacyPolicy: "Dasar Privasi",
  createAccountBtn: "Buat akaun",
  alreadyHaveAccount: "Sudah mempunyai akaun?",

  manageTitle: "Pengurusan Log Masuk",
  manageSubtitle: "Konfigurasikan penyedia SSO dan kaedah pengesahan.",
  addProvider: "Tambah Penyedia",
  usersLabel: "pengguna",
  lastSync: "Segerak terakhir",

  dashboardTitle: "Papan Pemuka",
  dashboardSubtitle: "Gambaran keseluruhan pengesahan dan kawalan akses.",
  statUsers: "Pengguna",
  statRoles: "Peranan",
  statProviders: "Penyedia",
  statActiveUsers: "Pengguna Aktif",
  statEnabled: "Dibenarkan",
  statDisabled: "Dilumpuhkan",

  permissionsTitle: "Kebenaran",
  managePermissions: "Urus definisi kebenaran dan jenis akses mereka.",
  addPermission: "Tambah Kebenaran",
  colPermName: "Nama Kebenaran",
  description: "Penerangan",
  colScope: "Skop",
  colTypes: "Jenis",
  colInfo: "Maklumat",
  colActions: "Tindakan",
  editPermission: "Sunting Kebenaran",
  permName: "Nama",
  scope: "Skop",
  phPermName: "Nama kebenaran",
  phPermDesc: "Penerangan kebenaran",
  phPermScope: "cth. Papan Pemuka, Portal HR",
  createPermission: "Cipta Kebenaran",
  savePermission: "Simpan Kebenaran",
  typeRead: "Baca",
  typeCreate: "Cipta",
  typeUpdate: "Kemas kini",
  typeDelete: "Padam",
  cancel: "Batal",
  edit: "Sunting",
  delete: "Padam",
  infoTitle: "Butiran",
  infoCreatedBy: "Dicipta Oleh",
  infoCreatedAt: "Dicipta Pada",
  infoUpdatedBy: "Dikemaskini Oleh",
  infoUpdatedAt: "Dikemaskini Pada",

  groupsTitle: "Peranan",
  manageGroups: "Urus peranan dan kebenaran yang diperuntukkan.",
  addGroup: "Tambah Peranan",
  groupName: "Nama Peranan",
  createGroup: "Cipta Peranan",
  editGroup: "Sunting Peranan",
  saveGroup: "Simpan Peranan",
  colPermissions: "Kebenaran",
  colMembers: "Ahli",
  phGroupName: "Nama peranan",
  phGroupDesc: "Penerangan peranan",

  manageUsersTitle: "Pengguna",
  manageUsersSubtitle: "Lihat semua pengguna dan peranan mereka mengikut penyedia.",
  colUser: "Pengguna",
  colProvider: "Penyedia",
  colRoleCount: "Peranan",
  colStatus: "Status",
  statusActive: "Aktif",
  statusLocked: "Dikunci",
  noUsersMatch: "Tiada pengguna sepadan dengan penapis semasa.",
  editUser: "Sunting Pengguna",
  saveUser: "Simpan Pengguna",
  labelName: "Nama",
  labelEmail: "E-mel",
  labelRole: "Peranan",
  labelStatus: "Status",
  phUserName: "Nama penuh",
  phUserEmail: "pengguna@syarikat.com",
  phUserDesc: "Penerangan pengguna",
  filterAllProviders: "Semua Penyedia",

  localManageTitle: "Log Masuk Tempatan",
  localManageSubtitle: "Urus akaun pengesahan tempatan.",
  addLogin: "Tambah Log Masuk",
  colUsername: "Nama Pengguna",
  colFullName: "Nama Penuh",
  colLastLogin: "Log Masuk Terakhir",
  colLastPwChange: "Tukar Kata Laluan Terakhir",
  createLogin: "Cipta Log Masuk",
  editLogin: "Sunting Log Masuk",
  saveLogin: "Simpan Log Masuk",
  labelPassword: "Kata Laluan",
  phUsername: "Nama pengguna",
  phPassword: "Tetapkan kata laluan awal",

  providersTitle: "Penyedia Jauh",
  providersSubtitle: "Urus penyedia SSO dan pengesahan jauh.",
  editProvider: "Sunting Penyedia",
  providerName: "Nama Penyedia",
  providerType: "Jenis Penyedia",
  labelEnabled: "Dibenarkan",
  labelUserCount: "Kiraan Pengguna",
  labelLastSync: "Segerak Terakhir",
  saveProvider: "Simpan Penyedia",
  createProvider: "Cipta Penyedia",
  phProviderName: "cth. Google Workspace",
  phProviderType: "cth. OAuth 2.0",

  navOverview: "Gambaran",
  navDashboard: "Papan Pemuka",
  navAccessControl: "Kawalan Akses",
  navAuthentication: "Pengesahan",
  navPermissions: "Kebenaran",
  navRoles: "Peranan",
  navManageUsers: "Pengguna",
  navLocalLogin: "Log Masuk Tempatan",
  navRemoteProviders: "Penyedia Jauh",
  members: "ahli",
  colUserCount: "Pengguna",
};

export default strings;
