import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  chooseProvider: "选择您的SSO提供商",
  selectProvider: "选择已配置的SSO提供商以继续",
  providerEntraId: "Microsoft Entra ID",
  providerGithub: "GitHub OAuth",
  providerOkta: "Okta",
  protocolSaml: "SAML 2.0",
  protocolOidc: "OIDC",
  continueWithProvider: "继续使用已选提供商",
  continueWithSSO: "继续使用SSO",
  orUse: "或使用",
  adLdap: "AD / LDAP",
  localAccount: "本地账户",
  pageSso: "第 1 页，共 3 页 - SSO 提供商",
  skipToLocal: "跳转到本地账户",

  localTitle: "本地",
  localSubtitle: "账户登录",
  localDesc: "使用用户名和密码登录",
  emailOrUsername: "邮箱或用户名",
  placeholderEmail: "you@company.com",
  password: "密码",
  enterPassword: "输入您的密码",
  rememberMe: "记住我",
  forgotPassword: "忘记密码？",
  signIn: "登录",
  orOtherMethods: "或使用其他方式",
  ssoProviders: "SSO 提供商",
  pageLocal: "第 3 页，共 3 页 - 本地认证",
  noAccount: "没有账户？",

  adTitle: "AD",
  adSubtitle: "/ LDAP 登录",
  adDesc: "输入您的域凭据",
  errorFillFields: "请填写所有字段",
  domain: "域名",
  placeholderDomain: "domain.local",
  username: "用户名",
  placeholderDomainUser: "DOMAIN\\username",
  networkPassword: "网络密码",
  rememberDomain: "记住域名",
  useLocalAccount: "使用本地账户",
  signInDomain: "登录到域",
  or: "或",
  backToSSO: "返回 SSO 提供商",
  pageAdLdap: "第 2 页，共 3 页 - AD/LDAP 认证",

  checkEmail: "查看您的邮箱",
  resetPassword: "重置密码",
  resetLinkSent: "如果该邮箱存在账户，您将很快收到重置链接。",
  resetDesc: "输入您的邮箱，我们将发送重置密码的链接。",
  tryAgain: "没有收到？再试一次",
  emailAddress: "邮箱地址",
  sendResetLink: "发送重置链接",
  backToLogin: "返回登录",

  registerTitle: "创建账户",
  registerDesc: `获取完整的 ${BRAND.name} 套件访问权限。`,
  firstName: "名",
  placeholderFirstName: "小明",
  lastName: "姓",
  placeholderLastName: "王",
  email: "邮箱",
  minChars: "最少 8 个字符",
  confirmPassword: "确认密码",
  reenterPassword: "重新输入密码",
  agreeTo: "我同意",
  and: "和",
  termsOfService: "服务条款",
  privacyPolicy: "隐私政策",
  createAccountBtn: "创建账户",
  alreadyHaveAccount: "已有账户？",

  manageTitle: "登录管理",
  manageSubtitle: "配置SSO提供商和身份验证方法。",
  addProvider: "添加提供商",
  usersLabel: "用户",
  lastSync: "上次同步",

  dashboardTitle: "仪表盘",
  dashboardSubtitle: "认证和访问控制概览。",
  statUsers: "用户",
  statRoles: "角色",
  statProviders: "提供商",
  statActiveUsers: "活跃用户",
  statEnabled: "已启用",
  statDisabled: "已禁用",

  permissionsTitle: "权限",
  managePermissions: "管理权限定义及其访问类型。",
  addPermission: "添加权限",
  colPermName: "权限名称",
  description: "描述",
  colScope: "范围",
  colTypes: "类型",
  colInfo: "信息",
  colActions: "操作",
  editPermission: "编辑权限",
  permName: "名称",
  scope: "范围",
  phPermName: "权限名称",
  phPermDesc: "权限描述",
  phPermScope: "例如 仪表盘、人力资源门户",
  createPermission: "创建权限",
  savePermission: "保存权限",
  typeRead: "读取",
  typeCreate: "创建",
  typeUpdate: "更新",
  typeDelete: "删除",
  cancel: "取消",
  edit: "编辑",
  delete: "删除",
  infoTitle: "详情",
  infoCreatedBy: "创建者",
  infoCreatedAt: "创建时间",
  infoUpdatedBy: "更新者",
  infoUpdatedAt: "更新时间",

  groupsTitle: "角色",
  manageGroups: "管理角色及其分配的权限。",
  addGroup: "添加角色",
  groupName: "角色名称",
  createGroup: "创建角色",
  editGroup: "编辑角色",
  saveGroup: "保存角色",
  colPermissions: "权限",
  colMembers: "成员",
  phGroupName: "角色名称",
  phGroupDesc: "角色描述",

  manageUsersTitle: "用户",
  manageUsersSubtitle: "查看所有用户及其在各提供商上的角色分配。",
  colUser: "用户",
  colProvider: "提供商",
  colRoleCount: "角色",
  colStatus: "状态",
  statusActive: "活跃",
  statusLocked: "已锁定",
  noUsersMatch: "没有用户匹配当前筛选条件。",
  editUser: "编辑用户",
  saveUser: "保存用户",
  labelName: "名称",
  labelEmail: "邮箱",
  labelRole: "角色",
  labelStatus: "状态",
  phUserName: "全名",
  phUserEmail: "user@company.com",
  phUserDesc: "用户描述",
  filterAllProviders: "所有提供商",

  localManageTitle: "本地登录",
  localManageSubtitle: "管理本地认证账户。",
  addLogin: "添加登录",
  colUsername: "用户名",
  colFullName: "全名",
  colLastLogin: "上次登录",
  colLastPwChange: "上次密码修改",
  createLogin: "创建登录",
  editLogin: "编辑登录",
  saveLogin: "保存登录",
  labelPassword: "密码",
  phUsername: "用户名",
  phPassword: "设置初始密码",

  providersTitle: "远程提供商",
  providersSubtitle: "管理SSO和远程认证提供商。",
  editProvider: "编辑提供商",
  providerName: "提供商名称",
  providerType: "提供商类型",
  labelEnabled: "已启用",
  labelUserCount: "用户数",
  labelLastSync: "上次同步",
  saveProvider: "保存提供商",
  createProvider: "创建提供商",
  phProviderName: "例如 Google Workspace",
  phProviderType: "例如 OAuth 2.0",

  navOverview: "概览",
  navDashboard: "仪表盘",
  navAccessControl: "访问控制",
  navAuthentication: "认证",
  navPermissions: "权限",
  navRoles: "角色",
  navManageUsers: "用户",
  navLocalLogin: "本地登录",
  navRemoteProviders: "远程提供商",
  members: "成员",
  colUserCount: "用户",
};

export default strings;
