import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  accountTitle: "Akaun",
  accountInfo: "Maklumat Akaun",
  accountInfoDesc: "Butiran akaun dan alamat e-mel anda",
  username: "Nama Pengguna",
  email: "E-mel",
  role: "Peranan",
  changePassword: "Tukar Kata Laluan",
  changePasswordDesc: "Kemas kini kata laluan anda untuk memastikan akaun selamat",
  currentPassword: "Kata Laluan Semasa",
  newPassword: "Kata Laluan Baharu",
  confirmNewPassword: "Sahkan Kata Laluan Baharu",
  saveChanges: "Simpan Perubahan",
  saved: "Disimpan",
  profileTitle: "Profil",
  profileDetails: "Butiran Profil",
  profileDesc: "Maklumat peribadi yang kelihatan kepada orang lain",
  fullName: "Nama Penuh",
  nickname: "Gelaran",
  bio: "Bio",
  location: "Lokasi",
  timezone: "Zon Waktu",
  saveProfile: "Simpan Profil",
  securityTitle: "Keselamatan",
  twoFactor: "Pengesahan Dua Faktor",
  twoFactorDesc: "Tambah lapisan keselamatan tambahan pada akaun anda",
  enable2fa: "Dayakan 2FA",
  enable2faDesc: "Lindungi akaun anda dengan aplikasi pengesah",
  disable2faDesc: "Pengesahan dua faktor telah didayakan",
  activeSessions: "Sesi Aktif",
  activeSessionsDesc: "Peranti yang sedang log masuk ke akaun anda",
  currentSession: "Sesi Semasa",
  chromeLinuxActive: "Chrome di Linux — Aktif sekarang",
  mobileApp: "Aplikasi Mudah Alih",
  iosTwoHoursAgo: "iOS — 2 jam lalu",
  revoke: "Batalkan",
  dangerZone: "Zon Berbahaya",
  dangerDesc: "Tindakan tidak boleh diubah kembali — berhati-hati",
  signOutEverywhere: "Log Keluar di Mana-mana",
  signOutEverywhereDesc: "Tamatkan semua sesi aktif kecuali ini",
  deleteAccount: "Padam Akaun",
  deleteAccountDesc: "Padam akaun anda dan semua data secara kekal",
  appearanceTitle: "Penampilan",
  themeTitle: "Tema",
  themeDesc: "Pilih skema warna pilihan anda",
  dark: "Gelap",
  light: "Cerah",
  contentWidthTitle: "Lebar Kandungan",
  contentWidthDesc: "Kawal berapa banyak ruang mendatar yang digunakan kandungan",
  narrow: "Sempit",
  narrowDesc: "Maks 768px — bacaan fokus",
  defaultWidth: "Lalai",
  defaultDesc: "Maks 1024px — susun atur seimbang",
  wide: "Lebar",
  wideDesc: "Maks 1280px — lebih banyak kandungan kelihatan",
  fullWidth: "Lebar Penuh",
  fullWidthDesc: "Gunakan keseluruhan viewport, bar sisi runtuh",
  displayTitle: "Paparan",
  displayDesc: "Laraskan keutamaan visual",
  fontScale: "Skala Fon",
  compactMode: "Mod Kompak",
  compactDesc: "Kurangkan jarak dan padding di seluruh UI",
  appearanceInfo: "Maklumat Akaun",
  navAccount: "Akaun",
  navAccountInfo: "Maklumat Akaun",
  navProfile: "Profil",
  navPreferences: "Keutamaan",
  navSecurity: "Keselamatan",
  navAppearance: "Penampilan",
  phEnterCurrentPassword: "Masukkan kata laluan semasa",
  phEnterNewPassword: "Masukkan kata laluan baharu",
  phConfirmNewPassword: "Sahkan kata laluan baharu",
  phYourFullName: "Nama penuh anda",
  phPreferredName: "Nama pilihan",
  phTellAboutYourself: "Ceritakan tentang diri anda...",
  phCityCountry: "Bandar, Negara",
  badgeActive: "Aktif",
  phYourEmail: "anda@emel.com",
};

export default strings;
