import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  accountTitle: "Account",
  accountInfo: "Account Information",
  accountInfoDesc: "Your account details and email address",
  username: "Username",
  email: "Email",
  role: "Role",
  changePassword: "Change Password",
  changePasswordDesc: "Update your password to keep your account secure",
  currentPassword: "Current Password",
  newPassword: "New Password",
  confirmNewPassword: "Confirm New Password",
  saveChanges: "Save Changes",
  saved: "Saved",
  profileTitle: "Profile",
  profileDetails: "Profile Details",
  profileDesc: "Personal information visible to others",
  fullName: "Full Name",
  nickname: "Nickname",
  bio: "Bio",
  location: "Location",
  timezone: "Timezone",
  saveProfile: "Save Profile",
  securityTitle: "Security",
  twoFactor: "Two-Factor Authentication",
  twoFactorDesc: "Add an extra layer of security to your account",
  enable2fa: "Enable 2FA",
  enable2faDesc: "Protect your account with an authenticator app",
  disable2faDesc: "Two-factor authentication is enabled",
  activeSessions: "Active Sessions",
  activeSessionsDesc: "Devices currently signed in to your account",
  currentSession: "Current Session",
  chromeLinuxActive: "Chrome on Linux — Active now",
  mobileApp: "Mobile App",
  iosTwoHoursAgo: "iOS — 2 hours ago",
  revoke: "Revoke",
  dangerZone: "Danger Zone",
  dangerDesc: "Irreversible actions — proceed with caution",
  signOutEverywhere: "Sign Out Everywhere",
  signOutEverywhereDesc: "End all active sessions except this one",
  deleteAccount: "Delete Account",
  deleteAccountDesc: "Permanently delete your account and all data",
  appearanceTitle: "Appearance",
  themeTitle: "Theme",
  themeDesc: "Choose your preferred color scheme",
  dark: "Dark",
  light: "Light",
  contentWidthTitle: "Content Width",
  contentWidthDesc: "Control how much horizontal space content uses",
  narrow: "Narrow",
  narrowDesc: "768px max — focused reading",
  defaultWidth: "Default",
  defaultDesc: "1024px max — balanced layout",
  wide: "Wide",
  wideDesc: "1280px max — more content visible",
  fullWidth: "Full Width",
  fullWidthDesc: "Uses entire viewport, sidebar collapses",
  displayTitle: "Display",
  displayDesc: "Adjust visual preferences",
  fontScale: "Font Scale",
  compactMode: "Compact Mode",
  compactDesc: "Reduce spacing and padding throughout the UI",
  appearanceInfo: "Account Info",
  navAccount: "Account",
  navAccountInfo: "Account Info",
  navProfile: "Profile",
  navPreferences: "Preferences",
  navSecurity: "Security",
  navAppearance: "Appearance",
  phEnterCurrentPassword: "Enter current password",
  phEnterNewPassword: "Enter new password",
  phConfirmNewPassword: "Confirm new password",
  phYourFullName: "Your full name",
  phPreferredName: "Preferred name",
  phTellAboutYourself: "Tell us about yourself...",
  phCityCountry: "City, Country",
};

export default strings;
