import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  accountTitle: "账户",
  accountInfo: "账户信息",
  accountInfoDesc: "您的账户详情和邮箱地址",
  username: "用户名",
  email: "邮箱",
  role: "角色",
  changePassword: "修改密码",
  changePasswordDesc: "更新您的密码以确保账户安全",
  currentPassword: "当前密码",
  newPassword: "新密码",
  confirmNewPassword: "确认新密码",
  saveChanges: "保存更改",
  saved: "已保存",
  profileTitle: "个人资料",
  profileDetails: "资料详情",
  profileDesc: "对其他人可见的个人信息",
  fullName: "全名",
  nickname: "昵称",
  bio: "简介",
  location: "位置",
  timezone: "时区",
  saveProfile: "保存资料",
  securityTitle: "安全",
  twoFactor: "两步验证",
  twoFactorDesc: "为您的账户添加额外的安全层",
  enable2fa: "启用两步验证",
  enable2faDesc: "使用验证器应用保护您的账户",
  disable2faDesc: "两步验证已启用",
  activeSessions: "活跃会话",
  activeSessionsDesc: "当前已登录到您账户的设备",
  currentSession: "当前会话",
  chromeLinuxActive: "Chrome on Linux — 当前活跃",
  mobileApp: "移动应用",
  iosTwoHoursAgo: "iOS — 2小时前",
  revoke: "撤销",
  dangerZone: "危险区域",
  dangerDesc: "不可逆操作 — 请谨慎操作",
  signOutEverywhere: "登出所有设备",
  signOutEverywhereDesc: "终止除当前会话外的所有活跃会话",
  deleteAccount: "删除账户",
  deleteAccountDesc: "永久删除您的账户和所有数据",
  appearanceTitle: "外观",
  themeTitle: "主题",
  themeDesc: "选择您偏好的配色方案",
  dark: "深色",
  light: "浅色",
  contentWidthTitle: "内容宽度",
  contentWidthDesc: "控制内容使用的水平空间",
  narrow: "窄",
  narrowDesc: "最大 768px — 专注阅读",
  defaultWidth: "默认",
  defaultDesc: "最大 1024px — 平衡布局",
  wide: "宽",
  wideDesc: "最大 1280px — 显示更多内容",
  fullWidth: "全宽",
  fullWidthDesc: "使用整个视口，侧栏折叠",
  displayTitle: "显示",
  displayDesc: "调整视觉偏好",
  fontScale: "字体缩放",
  compactMode: "紧凑模式",
  compactDesc: "减少整个 UI 的间距和内边距",
  appearanceInfo: "账户信息",
  navAccount: "账户",
  navAccountInfo: "账户信息",
  navProfile: "个人资料",
  navPreferences: "偏好设置",
  navSecurity: "安全",
  navAppearance: "外观",
  phEnterCurrentPassword: "输入当前密码",
  phEnterNewPassword: "输入新密码",
  phConfirmNewPassword: "确认新密码",
  phYourFullName: "您的全名",
  phPreferredName: "偏好名称",
  phTellAboutYourself: "介绍一下自己...",
  phCityCountry: "城市，国家",
};

export default strings;
