import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  setupTitle: "App Setup",
  setupDesc: "Configure your application for the first time",
  stepBranding: "Branding",
  stepDatabase: "Database",
  stepAdmin: "Admin Account",
  stepReview: "Review",
  appName: "Application Name",
  appLogo: "App Logo",
  uploadLogo: "Upload Logo",
  remove: "Remove",
  preview: "Preview",
  dbType: "Database Type",
  dbConnection: "Database Connection",
  dbSelectEngine: "Select your database engine and provide connection details.",
  hostname: "Hostname",
  port: "Port",
  username: "Username",
  dbPassword: "Password",
  schema: "Schema / Database Name",
  testConnection: "Test Connection",
  connectionSuccess: "Connection successful!",
  connectionFailed: "Connection failed. Check your credentials.",
  sqliteSelected: "SQLite Selected",
  sqliteInfo: "Data will be stored in a local file. No additional configuration needed.",
  localAdmin: "Local Admin Account",
  localAdminDesc: "Create the initial administrator account for local authentication.",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  passwordsNoMatch: "Passwords do not match",
  important: "Important",
  adminInfo: "This account will have full administrative privileges. Store these credentials securely.",
  reviewConfig: "Review Configuration",
  reviewDesc: "Verify your settings before completing the setup.",
  branding: "Branding",
  database: "Database",
  adminAccount: "Admin Account",
  host: "Host",
  user: "User",
  back: "Back",
  continue: "Continue",
  completeSetup: "Complete Setup",
  setupComplete: "Setup Complete!",
  redirecting: "Your application is ready. Redirecting...",
  stepOf: "Step",
  of: "of",
  svgPngJpg: "SVG, PNG or JPG. Max 2MB.",
  minChars: "Min. 4 characters",
  reenterPassword: "Re-enter password",
  dbPasswordPlaceholder: "Database password",
  brandingSubtext: "Set your application name and logo.",
  docsTitle: "Documentation",
  docsSubtitle: "Guides and references for",
  docsGettingStarted: "Getting Started",
  docsGettingStartedDesc: "Learn how to set up and configure your superapp gateway.",
  docsAuthentication: "Authentication",
  docsAuthenticationDesc: "Configure SSO providers, local auth, and role-based access.",
  docsAppManagement: "App Management",
  docsAppManagementDesc: "Register, configure, and manage application integrations.",
  docsPlaceholder: "Full documentation content will appear here.",
  backToApps: "Back to Apps",
  helpTitle: "Help Center",
  helpSubtitle: "Support resources for",
  helpFaq: "FAQ",
  helpFaqDesc: "Answers to frequently asked questions.",
  helpContact: "Contact Support",
  helpContactDesc: "Reach the team at",
  helpPlaceholder: "Additional help resources will appear here.",
};

export default strings;
