import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  setupTitle: "Persediaan Aplikasi",
  setupDesc: "Konfigurasikan aplikasi anda untuk kali pertama",
  stepBranding: "Pengjenamaan",
  stepDatabase: "Pangkalan Data",
  stepAdmin: "Akaun Pentadbir",
  stepReview: "Semakan",
  appName: "Nama Aplikasi",
  appLogo: "Logo Aplikasi",
  uploadLogo: "Muat Naik Logo",
  remove: "Buang",
  preview: "Pratonton",
  dbType: "Jenis Pangkalan Data",
  dbConnection: "Sambungan Pangkalan Data",
  dbSelectEngine: "Pilih enjin pangkalan data dan berikan butiran sambungan.",
  hostname: "Nama Hos",
  port: "Port",
  username: "Nama Pengguna",
  dbPassword: "Kata Laluan",
  schema: "Skema / Nama Pangkalan Data",
  testConnection: "Uji Sambungan",
  connectionSuccess: "Sambungan berjaya!",
  connectionFailed: "Sambungan gagal. Semak kelayakan anda.",
  sqliteSelected: "SQLite Dipilih",
  sqliteInfo: "Data akan disimpan dalam fail tempatan. Tiada konfigurasi tambahan diperlukan.",
  localAdmin: "Akaun Pentadbir Tempatan",
  localAdminDesc: "Cipta akaun pentadbir awal untuk pengesahan tempatan.",
  email: "E-mel",
  password: "Kata Laluan",
  confirmPassword: "Sahkan Kata Laluan",
  passwordsNoMatch: "Kata laluan tidak sepadan",
  important: "Penting",
  adminInfo: "Akaun ini akan mempunyai keistimewaan pentadbiran penuh. Simpan kelayakan ini dengan selamat.",
  reviewConfig: "Semak Konfigurasi",
  reviewDesc: "Sahkan tetapan anda sebelum menyelesaikan persediaan.",
  branding: "Pengjenamaan",
  database: "Pangkalan Data",
  adminAccount: "Akaun Pentadbir",
  host: "Hos",
  user: "Pengguna",
  back: "Kembali",
  continue: "Teruskan",
  completeSetup: "Selesaikan Persediaan",
  setupComplete: "Persediaan Selesai!",
  redirecting: "Aplikasi anda sudah siap. Mengalihkan...",
  stepOf: "Langkah",
  of: "daripada",
  svgPngJpg: "SVG, PNG atau JPG. Maks 2MB.",
  minChars: "Min. 4 aksara",
  reenterPassword: "Masukkan semula kata laluan",
  dbPasswordPlaceholder: "Kata laluan pangkalan data",
  brandingSubtext: "Tetapkan nama dan logo aplikasi anda.",
  docsTitle: "Dokumentasi",
  docsSubtitle: "Panduan dan rujukan untuk",
  docsGettingStarted: "Bermula",
  docsGettingStartedDesc: "Ketahui cara menyediakan dan mengkonfigurasi gerbang superapp anda.",
  docsAuthentication: "Pengesahan",
  docsAuthenticationDesc: "Konfigurasikan penyedia SSO, pengesahan tempatan, dan akses berasaskan peranan.",
  docsAppManagement: "Pengurusan Aplikasi",
  docsAppManagementDesc: "Daftar, konfigurasikan, dan urus integrasi aplikasi.",
  docsPlaceholder: "Kandungan dokumentasi penuh akan muncul di sini.",
  backToApps: "Kembali ke Aplikasi",
  helpTitle: "Pusat Bantuan",
  helpSubtitle: "Sumber sokongan untuk",
  helpFaq: "Soalan Lazim",
  helpFaqDesc: "Jawapan kepada soalan yang sering ditanya.",
  helpContact: "Hubungi Sokongan",
  helpContactDesc: "Hubungi pasukan di",
  helpPlaceholder: "Sumber bantuan tambahan akan muncul di sini.",
};

export default strings;
