import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  setupTitle: "应用设置",
  setupDesc: "首次配置您的应用程序",
  stepBranding: "品牌",
  stepDatabase: "数据库",
  stepAdmin: "管理员账户",
  stepReview: "审核",
  appName: "应用名称",
  appLogo: "应用图标",
  uploadLogo: "上传图标",
  remove: "移除",
  preview: "预览",
  dbType: "数据库类型",
  dbConnection: "数据库连接",
  dbSelectEngine: "选择数据库引擎并提供连接详情。",
  hostname: "主机名",
  port: "端口",
  username: "用户名",
  dbPassword: "密码",
  schema: "架构/数据库名称",
  testConnection: "测试连接",
  connectionSuccess: "连接成功！",
  connectionFailed: "连接失败。请检查您的凭据。",
  sqliteSelected: "已选择 SQLite",
  sqliteInfo: "数据将存储在本地文件中。无需额外配置。",
  localAdmin: "本地管理员账户",
  localAdminDesc: "创建用于本地认证的初始管理员账户。",
  email: "邮箱",
  password: "密码",
  confirmPassword: "确认密码",
  passwordsNoMatch: "密码不匹配",
  important: "重要",
  adminInfo: "此账户将拥有完整的管理员权限。请安全保存这些凭据。",
  reviewConfig: "审核配置",
  reviewDesc: "在完成设置前验证您的配置。",
  branding: "品牌",
  database: "数据库",
  adminAccount: "管理员账户",
  host: "主机",
  user: "用户",
  back: "返回",
  continue: "继续",
  completeSetup: "完成设置",
  setupComplete: "设置完成！",
  redirecting: "您的应用已就绪。正在跳转...",
  stepOf: "第",
  of: "步，共",
  svgPngJpg: "SVG、PNG 或 JPG。最大 2MB。",
  minChars: "最少 4 个字符",
  reenterPassword: "重新输入密码",
  dbPasswordPlaceholder: "数据库密码",
  brandingSubtext: "设置应用名称和图标。",
  docsTitle: "文档",
  docsSubtitle: "指南和参考资料 -",
  docsGettingStarted: "入门指南",
  docsGettingStartedDesc: "了解如何设置和配置超级应用网关。",
  docsAuthentication: "身份认证",
  docsAuthenticationDesc: "配置 SSO 提供商、本地认证和基于角色的访问。",
  docsAppManagement: "应用管理",
  docsAppManagementDesc: "注册、配置和管理应用集成。",
  docsPlaceholder: "完整文档内容将在此处显示。",
  backToApps: "返回应用",
  helpTitle: "帮助中心",
  helpSubtitle: "支持资源 -",
  helpFaq: "常见问题",
  helpFaqDesc: "常见问题的解答。",
  helpContact: "联系支持",
  helpContactDesc: "联系团队：",
  helpPlaceholder: "更多帮助资源将在此处显示。",
  phMyApp: "我的应用",
  phLocalhost: "localhost",
  phDbUser: "db_user",
  phSchemaDefault: "uiden",
  phAdminDefault: "admin",
  phAdminEmail: "admin@company.com",
  typeLabel: "类型",
  schemaLabel: "架构",
  reviewUsername: "用户名",
  reviewEmail: "邮箱",
  reviewPassword: "密码",
};

export default strings;
