import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  brandName: BRAND.name,
  welcomeTo: "Welcome to",
  welcomeUser: "Welcome,",
  filterApps: "Filter apps...",
  noAppsMatch: "No apps match",
  myApps: "My Apps",
  allApps: "All Apps",
  statusOnline: "Online",
  statusError: "Error",
  statusDown: "Down",
  statusMaintenance: "Maintenance",
  statusOk: "Operational",
  statusHidden: "Hidden",
  statusHide: "Hide",
  until: "until",
  manageTitle: "App Management",
  manageSubtitle: "Manage app status, availability, and role-based access.",
  dashboardTitle: "Dashboard",
  dashboardSubtitle: "Overview of registered apps and their status.",
  statusDistribution: "Status Distribution",
  pctOf: "of",
  manageStatusTitle: "App Status",
  manageStatusDesc: "Set app operational status. Down or maintenance apps show overlays on the app grid.",
  statusPageTitle: "Status",
  statusPageDesc: "Manage operational status for each registered app.",
  registrationTitle: "Registration",
  registeredCount: "registered apps",
  addApp: "Add App",
  editApp: "Edit App",
  appDetails: "App Details",
  colApp: "App",
  colStatus: "Status",
  colAppName: "App Name",
  colIcon: "Icon",
  colDescription: "Description",
  colPermissionPrefix: "Permission Prefix",
  colInfo: "Info",
  colActions: "Actions",
  colMaintenanceFrom: "Maintenance From",
  colMaintenanceTo: "Maintenance To",
  colMaintenanceUntil: "Maintenance Until",
  colRoles: "Roles",
  dash: "\u2014",
  maintenancePlaceholder: "e.g. 2025-05-10 18:00",
  labelAppName: "App Name",
  labelAppIcon: "App Icon",
  labelDescription: "Description",
  labelPermissionPrefix: "Permission Prefix",
  placeholderAppName: "e.g. My-App",
  placeholderAppIcon: "lucide:box",
  placeholderDescription: "App description...",
  placeholderPermissionPrefix: "e.g. my.app",
  cancel: "Cancel",
  create: "Create",
  save: "Save",
  detailIdSlug: "ID / Slug",
  detailName: "Name",
  detailCategory: "Category",
  detailPermissionPrefix: "Permission Prefix",
  detailCreatedBy: "Created By",
  detailCreatedAt: "Created At",
  detailUpdatedBy: "Updated By",
  detailUpdatedAt: "Updated At",
  navDocumentation: "Documentation",
  navHelp: "Help",
  navAbout: "About",
  statusInfoTitle: "Status History",
  statusCurrent: "Current Status",
  statusPrevious: "Previous Status",
  statusUpdatedBy: "Updated By",
  statusUpdatedAt: "Last Updated",
  statusNeverUpdated: "Never updated",
  colHistory: "History",
};

export default strings;
