import type { StringMap } from "~/lib/common/i18n";
import { BRAND } from "~/lib/common/branding";

const strings: StringMap = {
  brandName: BRAND.name,
  welcomeTo: "Selamat datang ke",
  welcomeUser: "Selamat datang,",
  filterApps: "Tapis aplikasi...",
  noAppsMatch: "Tiada aplikasi sepadan",
  myApps: "Aplikasi Saya",
  allApps: "Semua Aplikasi",
  statusOnline: "Dalam Talian",
  statusError: "Ralat",
  statusDown: "Tidak Berfungsi",
  statusMaintenance: "Penyelenggaraan",
  statusOk: "Beroperasi",
  statusHidden: "Tersembunyi",
  statusHide: "Sembunyikan",
  until: "hingga",
  manageTitle: "Pengurusan Aplikasi",
  manageSubtitle: "Urus status aplikasi, ketersediaan, dan akses berasaskan peranan.",
  dashboardTitle: "Papan Pemuka",
  dashboardSubtitle: "Gambaran keseluruhan aplikasi berdaftar dan status mereka.",
  statusDistribution: "Taburan Status",
  pctOf: "daripada",
  manageStatusTitle: "Status Aplikasi",
  manageStatusDesc: "Tetapkan status operasi aplikasi. Aplikasi yang tidak berfungsi atau dalam penyelenggaraan akan dipaparkan di grid.",
  statusPageTitle: "Status",
  statusPageDesc: "Urus status operasi untuk setiap aplikasi berdaftar.",
  registrationTitle: "Pendaftaran",
  registeredCount: "aplikasi berdaftar",
  addApp: "Tambah Aplikasi",
  editApp: "Edit Aplikasi",
  appDetails: "Butiran Aplikasi",
  colApp: "Aplikasi",
  colStatus: "Status",
  colAppName: "Nama Aplikasi",
  colIcon: "Ikon",
  colDescription: "Penerangan",
  colPermissionPrefix: "Awalan Kebenaran",
  colInfo: "Maklumat",
  colActions: "Tindakan",
  colMaintenanceFrom: "Penyelenggaraan Dari",
  colMaintenanceTo: "Penyelenggaraan Hingga",
  colMaintenanceUntil: "Penyelenggaraan Hingga",
  colRoles: "Peranan",
  dash: "\u2014",
  maintenancePlaceholder: "cth. 2025-05-10 18:00",
  labelAppName: "Nama Aplikasi",
  labelAppIcon: "Ikon Aplikasi",
  labelDescription: "Penerangan",
  labelPermissionPrefix: "Awalan Kebenaran",
  placeholderAppName: "cth. Aplikasi-Saya",
  placeholderAppIcon: "lucide:box",
  placeholderDescription: "Penerangan aplikasi...",
  placeholderPermissionPrefix: "cth. aplikasi.saya",
  cancel: "Batal",
  create: "Cipta",
  save: "Simpan",
  detailIdSlug: "ID / Slug",
  detailName: "Nama",
  detailCategory: "Kategori",
  detailPermissionPrefix: "Awalan Kebenaran",
  detailCreatedBy: "Dicipta Oleh",
  detailCreatedAt: "Dicipta Pada",
  detailUpdatedBy: "Dikemaskini Oleh",
  detailUpdatedAt: "Dikemaskini Pada",
  navDocumentation: "Dokumentasi",
  navHelp: "Bantuan",
  navAbout: "Tentang",
  statusInfoTitle: "Sejarah Status",
  statusCurrent: "Status Semasa",
  statusPrevious: "Status Sebelumnya",
  statusUpdatedBy: "Dikemaskini Oleh",
  statusUpdatedAt: "Kemas Kini Terakhir",
  statusNeverUpdated: "Tidak pernah dikemaskini",
  colHistory: "Sejarah",
};

export default strings;
