export const BRAND = {
  name: "Kentut SuperApp",
  shortName: "Kentut",
  tagline: "SuperApp",
  slug: "superapp",
  supportEmail: "support@kentut.superapp",
  docsUrl: "docs.kentut.superapp",
  description: "a unified gateway to all your enterprise tools",
} as const;

export const ROUTES = {
  home: "/apps",
  apps: "/apps",
  appManage: "/apps/manage",
  appManageRegistration: "/apps/manage/registration",
  appManageStatus: "/apps/manage/status",
  about: "/about",
  setupDocs: "/setup/docs",
  setupHelp: "/setup/help",
  setup: "/setup",
  login: "/login",
  loginLocal: "/login/local",
  loginAdLdap: "/login/ad-ldap",
  loginForgotPassword: "/login/forgot-password",
  loginRegister: "/login/register",
  loginManage: "/login/manage",
  loginManageLocal: "/login/manage/local",
  loginManageProviders: "/login/manage/providers",
  loginManageGroups: "/login/manage/groups",
  loginManagePermissions: "/login/manage/permissions",
  loginUsers: "/login/manage/local",
  loginGroups: "/login/manage/groups",
  loginPermissions: "/login/manage/permissions",
  userAccount: "/users/account",
  userProfile: "/users/profile",
  userSecurity: "/users/security",
  userAppearance: "/users/appearance",
} as const;
