import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  splashLoading: "Memuatkan",
  splashTagline: "Gerbang SuperApp Perusahaan",
  splashInitializing: "Memulakan...",
  splashEnter: "Masuk",
  poweredBy: "Dikuasakan oleh",
  home: "Utama",
  save: "Simpan",
  saved: "Disimpan",
  cancel: "Batal",
  close: "Tutup",
  confirm: "Sahkan",
  loading: "Memuatkan...",
  noData: "Tiada data",
  error: "Ralat",
  success: "Berjaya",
  search: "Carian",
  actions: "Tindakan",
  enabled: "Dibenarkan",
  disabled: "Dilumpuhkan",
  active: "Aktif",
  inactive: "Tidak Aktif",
  online: "Dalam Talian",
  offline: "Luar Talian",
  aboutTitle: "Tentang",
  aboutSubtitle: "Maklumat platform dan butiran versi.",
  aboutSuperapp: "Gerbang menyeluruh untuk semua alat perusahaan anda.",
  aboutVersion: "Versi",
  aboutFramework: "Rangka Kerja",
  aboutLicense: "Lesen",
  aboutPlaceholder: "Butiran tambahan akan muncul di sini.",
  backToApps: "Kembali ke Aplikasi",
  publicBadge: "Awam",
  publicLanding: "Ini adalah halaman pendaratan awam untuk",
  publicContentHere: "Kandungan dan ciri untuk aplikasi ini akan muncul di sini.",
  docsTitle: "Dokumentasi",
  docsSubtitle: "Panduan dan rujukan untuk",
  docsGettingStarted: "Bermula",
  docsGettingStartedApp: "Cara mengkonfigurasi dan menggunakan",
  docsPlaceholder: "Dokumentasi penuh untuk",
  docsPlaceholderSuffix: "akan muncul di sini.",
  docsBackTo: "Kembali ke",
  helpTitle: "Pusat Bantuan",
  helpSubtitle: "Sumber sokongan untuk",
  helpFaq: "Soalan Lazim",
  helpFaqApp: "Soalan dan jawapan biasa untuk",
  helpPlaceholder: "Kandungan bantuan untuk",
  helpPlaceholderSuffix: "akan muncul di sini.",
  helpContact: "Hubungi:",
  aboutAppTitle: "Tentang",
  aboutAppSubtitle: "Maklumat tentang",
  aboutCategory: "Kategori",
  aboutSlug: "Slug",
  aboutAppPlaceholder: "Butiran tambahan tentang",
  aboutAppPlaceholderSuffix: "akan muncul di sini.",
  privateDashboard: "Ini adalah papan pemuka peribadi untuk",
  privateContentHere: "Ciri dan kandungan yang disahkan akan muncul di sini.",
  navNavigation: "Navigasi",
  navDashboard: "Papan Pemuka",
  navOverview: "Gambaran",
  navPublicPage: "Halaman Awam",
  collapse: "Runtuhkan",
  searchApps: "Cari aplikasi...",
  noAppsFound: "Tiada aplikasi ditemui",
  helpInfo: "Bantuan & Maklumat",
  appManagement: "Pengurusan Aplikasi",
  loginManagement: "Pengurusan Log Masuk",
  userManagement: "Pengurusan Pengguna",
  userSettings: "Tetapan Pengguna",
  logout: "Log Keluar",
  signIn: "Log Masuk",
  appsCount: "aplikasi",
  switchToLight: "Tukar ke mod cerah",
  switchToDark: "Tukar ke mod gelap",
  docsBadge: "Docs",
  helpBadge: "Bantuan",
  aboutBadge: "Tentang",
};

export default strings;
