import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  splashLoading: "加载中",
  splashTagline: "企业超级应用网关",
  splashInitializing: "正在初始化...",
  splashEnter: "进入",
  poweredBy: "由",
  home: "首页",
  save: "保存",
  saved: "已保存",
  cancel: "取消",
  close: "关闭",
  confirm: "确认",
  loading: "加载中...",
  noData: "暂无数据",
  error: "错误",
  success: "成功",
  search: "搜索",
  actions: "操作",
  enabled: "已启用",
  disabled: "已禁用",
  active: "活跃",
  inactive: "未激活",
  online: "在线",
  offline: "离线",
  aboutTitle: "关于",
  aboutSubtitle: "平台信息和版本详情。",
  aboutSuperapp: "统一网关，连接所有企业工具。",
  aboutVersion: "版本",
  aboutFramework: "框架",
  aboutLicense: "许可证",
  aboutPlaceholder: "更多详情将在此处显示。",
  backToApps: "返回应用",
  publicBadge: "公开",
  publicLanding: "这是公开着陆页：",
  publicContentHere: "此应用的内容和功能将在此处显示。",
  docsTitle: "文档",
  docsSubtitle: "指南和参考资料 -",
  docsGettingStarted: "入门指南",
  docsGettingStartedApp: "如何配置和使用",
  docsPlaceholder: "完整文档：",
  docsPlaceholderSuffix: "将在此处显示。",
  docsBackTo: "返回",
  helpTitle: "帮助中心",
  helpSubtitle: "支持资源 -",
  helpFaq: "常见问题",
  helpFaqApp: "常见问题和解答：",
  helpPlaceholder: "帮助内容：",
  helpPlaceholderSuffix: "将在此处显示。",
  helpContact: "联系：",
  aboutAppTitle: "关于",
  aboutAppSubtitle: "关于",
  aboutCategory: "分类",
  aboutSlug: "标识",
  aboutAppPlaceholder: "更多关于",
  aboutAppPlaceholderSuffix: "的详情将在此处显示。",
  privateDashboard: "这是私有仪表板：",
  privateContentHere: "已认证的功能和内容将在此处显示。",
  navNavigation: "导航",
  navDashboard: "仪表板",
  navOverview: "概览",
  navPublicPage: "公开页面",
  collapse: "收起",
  searchApps: "搜索应用...",
  noAppsFound: "未找到应用",
  helpInfo: "帮助与信息",
  appManagement: "应用管理",
  loginManagement: "登录管理",
  userManagement: "用户管理",
  userSettings: "用户设置",
  logout: "退出登录",
  signIn: "登录",
  appsCount: "个应用",
  switchToLight: "切换到浅色模式",
  switchToDark: "切换到深色模式",
  docsBadge: "文档",
  helpBadge: "帮助",
  aboutBadge: "关于",
  searchPlaceholder: "搜索...",
  searchOrScope: "搜索或输入 / 按范围筛选...",
  searchSelectScope: "选择范围",
  searchRecent: "最近",
  searchSuggested: "推荐",
  searchNavigate: "导航",
  searchOpen: "打开",
  searchClose: "关闭",
  searchToScope: "按范围筛选",
  searchNoResults: "无搜索结果：",
  searchFilteredTo: "已筛选至",
  searchRemoveScope: "尝试移除范围以获取更多结果。",
  aboutLicenseMit: "MIT",
  aboutFrameworkSolid: "SolidStart 1.x",
};

export default strings;
