import type { StringMap } from "~/lib/common/i18n";

const strings: StringMap = {
  splashLoading: "Loading",
  splashTagline: "Enterprise SuperApp Gateway",
  splashInitializing: "Initializing...",
  splashEnter: "Enter",
  poweredBy: "Powered by",
  home: "Home",
  save: "Save",
  saved: "Saved",
  cancel: "Cancel",
  close: "Close",
  confirm: "Confirm",
  loading: "Loading...",
  noData: "No data",
  error: "Error",
  success: "Success",
  search: "Search",
  actions: "Actions",
  enabled: "Enabled",
  disabled: "Disabled",
  active: "Active",
  inactive: "Inactive",
  online: "Online",
  offline: "Offline",
  aboutTitle: "About",
  aboutSubtitle: "Platform information and version details.",
  aboutSuperapp: "A unified gateway to all your enterprise tools.",
  aboutVersion: "Version",
  aboutFramework: "Framework",
  aboutLicense: "License",
  aboutPlaceholder: "Additional about details will appear here.",
  backToApps: "Back to Apps",
  publicBadge: "Public",
  publicLanding: "This is the public landing page for",
  publicContentHere: "Content and features for this app will appear here.",
  docsTitle: "Documentation",
  docsSubtitle: "Guides and references for",
  docsGettingStarted: "Getting Started",
  docsGettingStartedApp: "How to configure and use",
  docsPlaceholder: "Full documentation for",
  docsPlaceholderSuffix: "will appear here.",
  docsBackTo: "Back to",
  helpTitle: "Help Center",
  helpSubtitle: "Support resources for",
  helpFaq: "FAQ",
  helpFaqApp: "Common questions and answers for",
  helpPlaceholder: "Help content for",
  helpPlaceholderSuffix: "will appear here.",
  helpContact: "Contact:",
  aboutAppTitle: "About",
  aboutAppSubtitle: "Information about",
  aboutCategory: "Category",
  aboutSlug: "Slug",
  aboutAppPlaceholder: "Additional about details for",
  aboutAppPlaceholderSuffix: "will appear here.",
  privateDashboard: "This is the private dashboard for",
  privateContentHere: "Authenticated features and content will appear here.",
  navNavigation: "Navigation",
  navDashboard: "Dashboard",
  navOverview: "Overview",
  navPublicPage: "Public Page",
  collapse: "Collapse",
  searchApps: "Search apps...",
  noAppsFound: "No apps found",
  helpInfo: "Help & Info",
  appManagement: "App Management",
  loginManagement: "Login Management",
  userManagement: "User Management",
  userSettings: "User Settings",
  logout: "Logout",
  signIn: "Sign in",
  appsCount: "apps",
  switchToLight: "Switch to light mode",
  switchToDark: "Switch to dark mode",
  docsBadge: "Docs",
  helpBadge: "Help",
  aboutBadge: "About",
  searchPlaceholder: "Search...",
  searchOrScope: "Search or type / to filter by scope...",
  searchSelectScope: "Select Scope",
  searchRecent: "Recent",
  searchSuggested: "Suggested",
  searchNavigate: "Navigate",
  searchOpen: "Open",
  searchClose: "Close",
  searchToScope: "to scope",
  searchNoResults: "No results for",
  searchFilteredTo: "Filtered to",
  searchRemoveScope: "Try removing the scope for broader results.",
  aboutLicenseMit: "MIT",
  aboutFrameworkSolid: "SolidStart 1.x",
};

export default strings;
